networks:
  StealTheCats:

services:
  localhost:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=kosmas123!@#
    networks:
     - StealTheCats
  stealthecatsfinal:
    container_name: steal_the_cats
    image: ${DOCKER_REGISTRY-}stealthecatsfinal
    build:
      context: .
      dockerfile: StealTheCatsFinal/Dockerfile
    ports:
        - 8001:8080
    depends_on:
    - localhost
    environment:
    - DB_HOST=localhost
    - DB_NAME=CatDB
    - DB_SA_PASSWORD=kosmas123!@#
    networks:
    - StealTheCats
